project_id = "kyxkvwxodyuqfzwjcyuc"

[functions.create-user]
verify_jwt = false

[functions.delete-user]
verify_jwt = false

[functions.reset-weekly-bookings]
verify_jwt = false

[functions.validate-qr]
verify_jwt = false

[functions.duplicate-weekly-schedules]
verify_jwt = false

[functions.check-renewals]
verify_jwt = false

[functions.check-birthdays]
verify_jwt = false
