workflows:
  ios-workflow:
    name: iOS App Store Build
    max_build_duration: 60
    instance_type: mac_mini_m2
    integrations:
      app_store_connect: Panthera Fitness Alburquerque
    environment:
      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.pantherafitness.alburquerque
      vars:
        XCODE_WORKSPACE: "ios/App/App.xcworkspace"
        XCODE_SCHEME: "App"
      node: v20.11.1
    scripts:
      - name: Install dependencies
        script: |
          npm install
      - name: Build web app
        script: |
          npm run build
      - name: Add iOS platform
        script: |
          npx cap add ios || true
          npx cap sync ios
      - name: Configure iOS App Icon
        script: |
          # Copy app icon to iOS project
          ICON_SOURCE="public/app-icon.png"
          ICON_DIR="ios/App/App/Assets.xcassets/AppIcon.appiconset"
          
          if [ -f "$ICON_SOURCE" ]; then
            # Generate all required iOS icon sizes using sips
            sips -z 20 20 "$ICON_SOURCE" --out "$ICON_DIR/AppIcon-20x20@1x.png"
            sips -z 40 40 "$ICON_SOURCE" --out "$ICON_DIR/AppIcon-20x20@2x.png"
            sips -z 60 60 "$ICON_SOURCE" --out "$ICON_DIR/AppIcon-20x20@3x.png"
            sips -z 29 29 "$ICON_SOURCE" --out "$ICON_DIR/AppIcon-29x29@1x.png"
            sips -z 58 58 "$ICON_SOURCE" --out "$ICON_DIR/AppIcon-29x29@2x.png"
            sips -z 87 87 "$ICON_SOURCE" --out "$ICON_DIR/AppIcon-29x29@3x.png"
            sips -z 40 40 "$ICON_SOURCE" --out "$ICON_DIR/AppIcon-40x40@1x.png"
            sips -z 80 80 "$ICON_SOURCE" --out "$ICON_DIR/AppIcon-40x40@2x.png"
            sips -z 120 120 "$ICON_SOURCE" --out "$ICON_DIR/AppIcon-40x40@3x.png"
            sips -z 120 120 "$ICON_SOURCE" --out "$ICON_DIR/AppIcon-60x60@2x.png"
            sips -z 180 180 "$ICON_SOURCE" --out "$ICON_DIR/AppIcon-60x60@3x.png"
            sips -z 76 76 "$ICON_SOURCE" --out "$ICON_DIR/AppIcon-76x76@1x.png"
            sips -z 152 152 "$ICON_SOURCE" --out "$ICON_DIR/AppIcon-76x76@2x.png"
            sips -z 167 167 "$ICON_SOURCE" --out "$ICON_DIR/AppIcon-83.5x83.5@2x.png"
            sips -z 1024 1024 "$ICON_SOURCE" --out "$ICON_DIR/AppIcon-1024x1024@1x.png"
            
            # Update Contents.json for iOS icons
            cat > "$ICON_DIR/Contents.json" << 'EOF'
          {
            "images" : [
              { "filename" : "AppIcon-20x20@1x.png", "idiom" : "iphone", "scale" : "1x", "size" : "20x20" },
              { "filename" : "AppIcon-20x20@2x.png", "idiom" : "iphone", "scale" : "2x", "size" : "20x20" },
              { "filename" : "AppIcon-20x20@3x.png", "idiom" : "iphone", "scale" : "3x", "size" : "20x20" },
              { "filename" : "AppIcon-29x29@1x.png", "idiom" : "iphone", "scale" : "1x", "size" : "29x29" },
              { "filename" : "AppIcon-29x29@2x.png", "idiom" : "iphone", "scale" : "2x", "size" : "29x29" },
              { "filename" : "AppIcon-29x29@3x.png", "idiom" : "iphone", "scale" : "3x", "size" : "29x29" },
              { "filename" : "AppIcon-40x40@1x.png", "idiom" : "iphone", "scale" : "1x", "size" : "40x40" },
              { "filename" : "AppIcon-40x40@2x.png", "idiom" : "iphone", "scale" : "2x", "size" : "40x40" },
              { "filename" : "AppIcon-40x40@3x.png", "idiom" : "iphone", "scale" : "3x", "size" : "40x40" },
              { "filename" : "AppIcon-60x60@2x.png", "idiom" : "iphone", "scale" : "2x", "size" : "60x60" },
              { "filename" : "AppIcon-60x60@3x.png", "idiom" : "iphone", "scale" : "3x", "size" : "60x60" },
              { "filename" : "AppIcon-20x20@1x.png", "idiom" : "ipad", "scale" : "1x", "size" : "20x20" },
              { "filename" : "AppIcon-20x20@2x.png", "idiom" : "ipad", "scale" : "2x", "size" : "20x20" },
              { "filename" : "AppIcon-29x29@1x.png", "idiom" : "ipad", "scale" : "1x", "size" : "29x29" },
              { "filename" : "AppIcon-29x29@2x.png", "idiom" : "ipad", "scale" : "2x", "size" : "29x29" },
              { "filename" : "AppIcon-40x40@1x.png", "idiom" : "ipad", "scale" : "1x", "size" : "40x40" },
              { "filename" : "AppIcon-40x40@2x.png", "idiom" : "ipad", "scale" : "2x", "size" : "40x40" },
              { "filename" : "AppIcon-76x76@1x.png", "idiom" : "ipad", "scale" : "1x", "size" : "76x76" },
              { "filename" : "AppIcon-76x76@2x.png", "idiom" : "ipad", "scale" : "2x", "size" : "76x76" },
              { "filename" : "AppIcon-83.5x83.5@2x.png", "idiom" : "ipad", "scale" : "2x", "size" : "83.5x83.5" },
              { "filename" : "AppIcon-1024x1024@1x.png", "idiom" : "ios-marketing", "scale" : "1x", "size" : "1024x1024" }
            ],
            "info" : { "author" : "xcode", "version" : 1 }
          }
          EOF
            echo "iOS app icons configured successfully"
          else
            echo "Warning: App icon not found at $ICON_SOURCE"
          fi
      - name: Install CocoaPods dependencies
        script: |
          cd ios/App && pod install
      - name: Set up code signing
        script: |
          xcode-project use-profiles
      - name: Build IPA
        script: |
          xcode-project build-ipa \
            --workspace "$XCODE_WORKSPACE" \
            --scheme "$XCODE_SCHEME"
    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
    publishing:
      app_store_connect:
        auth: integration
        submit_to_testflight: true
