workflows:
  ios-workflow:
    name: iOS App Store Build
    max_build_duration: 60
    instance_type: mac_mini_m2
    integrations:
      app_store_connect: Panthera Fitness Alburquerque
    environment:
      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.pantherafitness.alburquerque
      vars:
        XCODE_WORKSPACE: "ios/App/App.xcworkspace"
        XCODE_SCHEME: "App"
      node: v20.11.1
    scripts:
      - name: Install dependencies
        script: |
          # Deterministic install based on package-lock.
          # legacy-peer-deps avoids common peer-deps resolution failures in CI.
          npm ci --legacy-peer-deps
      - name: Build web app
        script: |
          npm run build
      - name: Add iOS platform
        script: |
          npx cap add ios || true
      - name: Set iOS deployment target (required by CapacitorCamera)
        script: |
          # CapacitorCamera 8.x requires iOS 15+. Update Podfile and project.pbxproj.
          PODFILE="ios/App/Podfile"
          PBXPROJ="ios/App/App.xcodeproj/project.pbxproj"
          
          # Update Podfile
          if [ -f "$PODFILE" ]; then
            # If there's no platform line yet, add it at the top.
            if ! grep -q "^platform :ios" "$PODFILE"; then
              perl -0777 -i -pe "s/^/platform :ios, '15.0'\n/" "$PODFILE"
            fi
            # Use perl for reliable in-place replacement (macOS sed can be tricky)
            perl -i -pe "s/platform :ios, '[0-9.]+'/platform :ios, '15.0'/g" "$PODFILE"
            echo "Podfile updated:"
            grep "platform :ios" "$PODFILE" || true
          fi
          
          # Update project.pbxproj deployment target
          if [ -f "$PBXPROJ" ]; then
            perl -i -pe "s/IPHONEOS_DEPLOYMENT_TARGET = [0-9.]+;/IPHONEOS_DEPLOYMENT_TARGET = 15.0;/g" "$PBXPROJ"
            echo "project.pbxproj IPHONEOS_DEPLOYMENT_TARGET updated to 15.0"
          fi
      - name: Configure Info.plist permissions
        script: |
          INFO_PLIST="ios/App/App/Info.plist"
          
          if [ -f "$INFO_PLIST" ]; then
            # Add Camera usage description (required for profile photo)
            /usr/libexec/PlistBuddy -c "Add :NSCameraUsageDescription string 'Panthera Fitness necesita acceso a la cámara para tomar fotos de perfil'" "$INFO_PLIST" 2>/dev/null || \
            /usr/libexec/PlistBuddy -c "Set :NSCameraUsageDescription 'Panthera Fitness necesita acceso a la cámara para tomar fotos de perfil'" "$INFO_PLIST"
            
            # Add Photo Library usage description
            /usr/libexec/PlistBuddy -c "Add :NSPhotoLibraryUsageDescription string 'Panthera Fitness necesita acceso a tus fotos para seleccionar una foto de perfil'" "$INFO_PLIST" 2>/dev/null || \
            /usr/libexec/PlistBuddy -c "Set :NSPhotoLibraryUsageDescription 'Panthera Fitness necesita acceso a tus fotos para seleccionar una foto de perfil'" "$INFO_PLIST"

            # Add Photo Library Add usage description (some camera flows require it)
            /usr/libexec/PlistBuddy -c "Add :NSPhotoLibraryAddUsageDescription string 'Panthera Fitness necesita permiso para guardar la foto tomada (si el sistema lo requiere)'" "$INFO_PLIST" 2>/dev/null || \
            /usr/libexec/PlistBuddy -c "Set :NSPhotoLibraryAddUsageDescription 'Panthera Fitness necesita permiso para guardar la foto tomada (si el sistema lo requiere)'" "$INFO_PLIST"
            
            echo "Info.plist permissions configured successfully"
          else
            echo "Warning: Info.plist not found at $INFO_PLIST"
          fi
      - name: Sync iOS platform
        script: |
          # Allow this step to continue even if CocoaPods fails here.
          # We'll run a controlled `pod install` after forcing deployment targets.
          npx cap sync ios || true
      - name: Configure iOS App Icon
        script: |
          # Copy app icon to iOS project
          ICON_SOURCE="public/app-icon.png"
          ICON_DIR="ios/App/App/Assets.xcassets/AppIcon.appiconset"
          
          if [ -f "$ICON_SOURCE" ]; then
            # Generate all required iOS icon sizes using sips
            sips -z 20 20 "$ICON_SOURCE" --out "$ICON_DIR/AppIcon-20x20@1x.png"
            sips -z 40 40 "$ICON_SOURCE" --out "$ICON_DIR/AppIcon-20x20@2x.png"
            sips -z 60 60 "$ICON_SOURCE" --out "$ICON_DIR/AppIcon-20x20@3x.png"
            sips -z 29 29 "$ICON_SOURCE" --out "$ICON_DIR/AppIcon-29x29@1x.png"
            sips -z 58 58 "$ICON_SOURCE" --out "$ICON_DIR/AppIcon-29x29@2x.png"
            sips -z 87 87 "$ICON_SOURCE" --out "$ICON_DIR/AppIcon-29x29@3x.png"
            sips -z 40 40 "$ICON_SOURCE" --out "$ICON_DIR/AppIcon-40x40@1x.png"
            sips -z 80 80 "$ICON_SOURCE" --out "$ICON_DIR/AppIcon-40x40@2x.png"
            sips -z 120 120 "$ICON_SOURCE" --out "$ICON_DIR/AppIcon-40x40@3x.png"
            sips -z 120 120 "$ICON_SOURCE" --out "$ICON_DIR/AppIcon-60x60@2x.png"
            sips -z 180 180 "$ICON_SOURCE" --out "$ICON_DIR/AppIcon-60x60@3x.png"
            sips -z 76 76 "$ICON_SOURCE" --out "$ICON_DIR/AppIcon-76x76@1x.png"
            sips -z 152 152 "$ICON_SOURCE" --out "$ICON_DIR/AppIcon-76x76@2x.png"
            sips -z 167 167 "$ICON_SOURCE" --out "$ICON_DIR/AppIcon-83.5x83.5@2x.png"
            sips -z 1024 1024 "$ICON_SOURCE" --out "$ICON_DIR/AppIcon-1024x1024@1x.png"
            
            # Update Contents.json for iOS icons
            cat > "$ICON_DIR/Contents.json" << 'EOF'
          {
            "images" : [
              { "filename" : "AppIcon-20x20@1x.png", "idiom" : "iphone", "scale" : "1x", "size" : "20x20" },
              { "filename" : "AppIcon-20x20@2x.png", "idiom" : "iphone", "scale" : "2x", "size" : "20x20" },
              { "filename" : "AppIcon-20x20@3x.png", "idiom" : "iphone", "scale" : "3x", "size" : "20x20" },
              { "filename" : "AppIcon-29x29@1x.png", "idiom" : "iphone", "scale" : "1x", "size" : "29x29" },
              { "filename" : "AppIcon-29x29@2x.png", "idiom" : "iphone", "scale" : "2x", "size" : "29x29" },
              { "filename" : "AppIcon-29x29@3x.png", "idiom" : "iphone", "scale" : "3x", "size" : "29x29" },
              { "filename" : "AppIcon-40x40@1x.png", "idiom" : "iphone", "scale" : "1x", "size" : "40x40" },
              { "filename" : "AppIcon-40x40@2x.png", "idiom" : "iphone", "scale" : "2x", "size" : "40x40" },
              { "filename" : "AppIcon-40x40@3x.png", "idiom" : "iphone", "scale" : "3x", "size" : "40x40" },
              { "filename" : "AppIcon-60x60@2x.png", "idiom" : "iphone", "scale" : "2x", "size" : "60x60" },
              { "filename" : "AppIcon-60x60@3x.png", "idiom" : "iphone", "scale" : "3x", "size" : "60x60" },
              { "filename" : "AppIcon-20x20@1x.png", "idiom" : "ipad", "scale" : "1x", "size" : "20x20" },
              { "filename" : "AppIcon-20x20@2x.png", "idiom" : "ipad", "scale" : "2x", "size" : "20x20" },
              { "filename" : "AppIcon-29x29@1x.png", "idiom" : "ipad", "scale" : "1x", "size" : "29x29" },
              { "filename" : "AppIcon-29x29@2x.png", "idiom" : "ipad", "scale" : "2x", "size" : "29x29" },
              { "filename" : "AppIcon-40x40@1x.png", "idiom" : "ipad", "scale" : "1x", "size" : "40x40" },
              { "filename" : "AppIcon-40x40@2x.png", "idiom" : "ipad", "scale" : "2x", "size" : "40x40" },
              { "filename" : "AppIcon-76x76@1x.png", "idiom" : "ipad", "scale" : "1x", "size" : "76x76" },
              { "filename" : "AppIcon-76x76@2x.png", "idiom" : "ipad", "scale" : "2x", "size" : "76x76" },
              { "filename" : "AppIcon-83.5x83.5@2x.png", "idiom" : "ipad", "scale" : "2x", "size" : "83.5x83.5" },
              { "filename" : "AppIcon-1024x1024@1x.png", "idiom" : "ios-marketing", "scale" : "1x", "size" : "1024x1024" }
            ],
            "info" : { "author" : "xcode", "version" : 1 }
          }
          EOF
            echo "iOS app icons configured successfully"
          else
            echo "Warning: App icon not found at $ICON_SOURCE"
          fi
      - name: Configure device family (iPhone + iPad)
        script: |
          PBXPROJ="ios/App/App.xcodeproj/project.pbxproj"
          
          if [ -f "$PBXPROJ" ]; then
            # TARGETED_DEVICE_FAMILY: 1 = iPhone, 2 = iPad, "1,2" = Universal
            perl -i -pe 's/TARGETED_DEVICE_FAMILY = "[^"]*";/TARGETED_DEVICE_FAMILY = "1,2";/g' "$PBXPROJ"
            perl -i -pe 's/TARGETED_DEVICE_FAMILY = [0-9]+;/TARGETED_DEVICE_FAMILY = "1,2";/g' "$PBXPROJ"
            echo "TARGETED_DEVICE_FAMILY set to 1,2 (iPhone + iPad)"
          else
            echo "Warning: project.pbxproj not found"
          fi
      - name: Install CocoaPods dependencies
        script: |
          # Force a higher iOS deployment target so CocoaPods can resolve CapacitorCamera.
          PODFILE="ios/App/Podfile"
          PBXPROJ="ios/App/App.xcodeproj/project.pbxproj"

          if [ -f "$PODFILE" ]; then
            # Ensure platform line
            if ! grep -q "^platform :ios" "$PODFILE"; then
              perl -0777 -i -pe "s/^/platform :ios, '15.0'\n/" "$PODFILE"
            fi
            perl -i -pe "s/platform :ios, '[0-9.]+'/platform :ios, '15.0'/g" "$PODFILE"

            # Ensure post_install forces deployment target on all pods (using echo to avoid YAML issues)
            if ! grep -q "post_install do" "$PODFILE"; then
              echo "" >> "$PODFILE"
              echo "post_install do |installer|" >> "$PODFILE"
              echo "  installer.pods_project.targets.each do |target|" >> "$PODFILE"
              echo "    target.build_configurations.each do |config|" >> "$PODFILE"
              echo "      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '15.0'" >> "$PODFILE"
              echo "    end" >> "$PODFILE"
              echo "  end" >> "$PODFILE"
              echo "end" >> "$PODFILE"
            fi

            echo "Podfile platform/deployment target forced to 15.0"
            cat "$PODFILE"
          else
            echo "Warning: Podfile not found at $PODFILE"
          fi

          if [ -f "$PBXPROJ" ]; then
            perl -i -pe "s/IPHONEOS_DEPLOYMENT_TARGET = [0-9.]+;/IPHONEOS_DEPLOYMENT_TARGET = 15.0;/g" "$PBXPROJ"
            echo "project.pbxproj IPHONEOS_DEPLOYMENT_TARGET forced to 15.0"
          fi

          cd ios/App && pod repo update && pod install
      - name: Set up code signing
        script: |
          xcode-project use-profiles
      - name: Set iOS build number (avoid duplicate uploads)
        script: |
          BUILD_NO="${BUILD_NUMBER:-${CM_BUILD_NUMBER:-1}}"
          INFO_PLIST="ios/App/App/Info.plist"

          if [ -f "$INFO_PLIST" ]; then
            /usr/libexec/PlistBuddy -c "Set :CFBundleVersion $BUILD_NO" "$INFO_PLIST" || \
            /usr/libexec/PlistBuddy -c "Add :CFBundleVersion string $BUILD_NO" "$INFO_PLIST"
            echo "Set CFBundleVersion to $BUILD_NO"
          else
            echo "Warning: Info.plist not found at $INFO_PLIST"
            ls -la ios/App/App || true
          fi
      - name: Build IPA
        script: |
          xcode-project build-ipa \
            --workspace "$XCODE_WORKSPACE" \
            --scheme "$XCODE_SCHEME"
    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
    publishing:
      app_store_connect:
        auth: integration
        submit_to_testflight: true
